-- Habilitar extensiones si es necesario (generalmente uuid-ossp está habilitada por defecto)
create extension if not exists "uuid-ossp";

-- 1. Tabla de Categorías
create table if not exists public.categorias (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    creado_en timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insertar categorías semilla
insert into public.categorias (nombre) values 
('Novelas'),
('Infantil'),
('Escolar'),
('Utiles')
on conflict (nombre) do nothing;

-- 2. Tabla de Productos
create table if not exists public.productos (
    id bigint generated by default as identity primary key,
    nombre text not null,
    categoria_id bigint references public.categorias(id) on delete set null,
    precio numeric(10,2) not null default 0.00,
    imagen_url text,
    creado_en timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabla de Stock (Relación 1:1 con Productos para emular el mockup)
create table if not exists public.stock (
    producto_id bigint references public.productos(id) on delete cascade primary key,
    deposito integer not null default 0,
    sucursal1 integer not null default 0,
    sucursal2 integer not null default 0,
    online integer not null default 0
);

-- 4. Tabla de Ventas (Punto de Venta POS)
create table if not exists public.ventas (
    id bigint generated by default as identity primary key,
    fecha timestamp with time zone default timezone('utc'::text, now()) not null,
    total numeric(10,2) not null default 0.00,
    cliente text default 'Consumidor Final'
);

-- 5. Tabla de Pedidos Online
create table if not exists public.pedidos_online (
    id bigint generated by default as identity primary key,
    numero integer not null unique,
    cliente text not null,
    productos text not null, -- Guardaremos el listado detallado en texto
    total numeric(10,2) not null default 0.00,
    estado text not null default 'pendiente',
    creado_en timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Perfiles de Usuarios (vinculados a Supabase Auth)
create table if not exists public.perfiles (
    id uuid references auth.users(id) on delete cascade primary key,
    nombre text,
    rol text not null default 'admin',
    creado_en timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Row Level Security)
alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.stock enable row level security;
alter table public.ventas enable row level security;
alter table public.pedidos_online enable row level security;
alter table public.perfiles enable row level security;

-- Eliminar políticas previas para evitar errores de duplicación si se vuelve a correr
drop policy if exists "Permitir lectura publica de categorias" on public.categorias;
drop policy if exists "Permitir lectura publica de productos" on public.productos;
drop policy if exists "Permitir lectura publica de stock" on public.stock;
drop policy if exists "Permitir todo a usuarios autenticados en categorias" on public.categorias;
drop policy if exists "Permitir todo a usuarios autenticados en productos" on public.productos;
drop policy if exists "Permitir todo a usuarios autenticados en stock" on public.stock;
drop policy if exists "Permitir todo a usuarios autenticados en ventas" on public.ventas;
drop policy if exists "Permitir todo a usuarios autenticados en pedidos" on public.pedidos_online;
drop policy if exists "Permitir todo a usuarios autenticados en perfiles" on public.perfiles;
drop policy if exists "Permitir crear ventas anonimamente" on public.ventas;
drop policy if exists "Permitir crear pedidos anonimamente" on public.pedidos_online;

-- Políticas de RLS
-- Permitir lectura pública a categorías, productos y stock para la tienda online
create policy "Permitir lectura publica de categorias" on public.categorias for select using (true);
create policy "Permitir lectura publica de productos" on public.productos for select using (true);
create policy "Permitir lectura publica de stock" on public.stock for select using (true);

-- Permitir a usuarios autenticados realizar todas las acciones
create policy "Permitir todo a usuarios autenticados en categorias" on public.categorias for all using (auth.role() = 'authenticated');
create policy "Permitir todo a usuarios autenticados en productos" on public.productos for all using (auth.role() = 'authenticated');
create policy "Permitir todo a usuarios autenticados en stock" on public.stock for all using (auth.role() = 'authenticated');
create policy "Permitir todo a usuarios autenticados en ventas" on public.ventas for all using (auth.role() = 'authenticated');
create policy "Permitir todo a usuarios autenticados en pedidos" on public.pedidos_online for all using (auth.role() = 'authenticated');
create policy "Permitir todo a usuarios autenticados en perfiles" on public.perfiles for all using (auth.role() = 'authenticated');

-- Permitir a la tienda pública crear ventas y pedidos de manera anónima
create policy "Permitir crear ventas anonimamente" on public.ventas for insert with check (true);
create policy "Permitir crear pedidos anonimamente" on public.pedidos_online for insert with check (true);

-- Trigger para crear perfil automáticamente al registrarse en Supabase Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.perfiles (id, nombre, rol)
  values (new.id, coalesce(new.raw_user_meta_data->>'nombre', new.email), coalesce(new.raw_user_meta_data->>'rol', 'admin'));
  return new;
end;
$$ language plpgsql security definer;

-- Crear el trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
